// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/keith-cullen/microservice/store/ent/schema"
	"github.com/keith-cullen/microservice/store/ent/thing"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	thingFields := schema.Thing{}.Fields()
	_ = thingFields
	// thingDescName is the schema descriptor for name field.
	thingDescName := thingFields[0].Descriptor()
	// thing.DefaultName holds the default value on creation for the name field.
	thing.DefaultName = thingDescName.Default.(string)
}
