// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ThingsColumns holds the columns for the "things" table.
	ThingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// ThingsTable holds the schema information for the "things" table.
	ThingsTable = &schema.Table{
		Name:       "things",
		Columns:    ThingsColumns,
		PrimaryKey: []*schema.Column{ThingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ThingsTable,
	}
)

func init() {
}
